# [Python Reference Link](http://www.data8.org/sp20/python-reference.html)
*Run the cell below so that we can set our modules up*

In [1]:
import numpy as np
from datascience import *
import math

# Numbers

In [2]:
10/3

3.3333333333333335

In [3]:
3

3

In [4]:
3.0

3.0

In [5]:
1.329487569238476592348765293456293478650234875029438

1.3294875692384767

In [6]:
123.5**123

1.8838043016463903e+257

# Strings

In [7]:
'Here is a string'

'Here is a string'

In [8]:
"Here is a string as well"

'Here is a string as well'

In [9]:
greeting = 'hi, wassup'

In [10]:
greeting

'hi, wassup'

In [11]:
greeting +' class'

'hi, wassup class'

In [12]:
x = 'ha'
'mua'+x*10

'muahahahahahahahahahaha'

# Types

In [14]:
str(5678)

'5678'

In [15]:
float(str(5678))

5678.0

In [16]:
type(greeting)

str

In [17]:
abs?

Signature: abs(x, /)
Docstring: Return the absolute value of the argument.
Type:      builtin_function_or_method

# Looking at the difference between Strings, Ints, and Floats

In [18]:
print('4'+'4')
print(4+4)

44
8


# Arrays and the [NumPy Module](https://numpy.org/doc/stable/reference/index.html)

In [19]:
first_four = make_array(1,2,3,4)

In [20]:
first_four

array([1, 2, 3, 4])

In [21]:
first_four * 4

array([ 4,  8, 12, 16])

In [22]:
random = make_array(1,4,"this string")

In [23]:
random*4

TypeError: The 'out' kwarg is necessary when using the string multiply ufunc directly. Use numpy.strings.multiply to multiply strings without specifying 'out'.

# `np.arange` from the [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) module

In [24]:
#np.arange(stop)
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [25]:
#np.arange(start,stop)
np.arange(6,10)

array([6, 7, 8, 9])

In [28]:
#np.arange(start,stop,step)
np.arange(2,9,3)

array([2, 5, 8])

# Table Operations 

I strongly recommend adding the [Python Reference Page](https://www.data8.org/sp20/python-reference.html) to your bookmarks for reference! It is a sort of cheat sheet for the course! 

### Importing a Table
First, we will start with looking at how to import our data into the notebook:
<img src="Creating_Table.png" alt="drawing" width="1200"/>
*From the Python reference page

In [29]:
spotify = Table().read_table('spotify_songs.csv')
spotify

track_id               | track_name                                            | track_artist     | track_popularity | track_album_id         | track_album_name                                      | track_album_release_date | playlist_name | playlist_id            | playlist_genre | playlist_subgenre | danceability | energy | key  | loudness | mode | speechiness | acousticness | instrumentalness | liveness | valence | tempo   | duration_ms
6f807x0ima9a1j3VPbc7VN | I Don't Care (with Justin Bieber) - Loud Luxury Remix | Ed Sheeran       | 66               | 2oCs0DGTsRO98Gh5ZSl2Cx | I Don't Care (with Justin Bieber) [Loud Luxury Remix] | 2019-06-14               | Pop Remix     | 37i9dQZF1DXcZDD7cfEKhW | pop            | dance pop         | 0.748        | 0.916  | 6    | -2.634   | 1    | 0.0583      | 0.102        | 0                | 0.0653   | 0.518   | 122.036 | 194754
0r7CVbZTWZgbTCYdfa2P31 | Memories - Dillon Francis Remix                       | Maroon 5         | 67               | 63rPSO264uRjW1X5E6cWv6 | Memories (Dillon Francis Remix)                       | 2019-12-13               | Pop Remix     | 37i9dQZF1DXcZDD7cfEKhW | pop            | dance pop         | 0.726        | 0.815  | 11   | -4.969   | 1    | 0.0373      | 0.0724       | 0.00421          | 0.357    | 0.693   | 99.972  | 162600
1z1Hg7Vb0AhHDiEmnDE79l | All the Time - Don Diablo Remix                       | Zara Larsson     | 70               | 1HoSmj2eLcsrR0vE9gThr4 | All the Time (Don Diablo Remix)                       | 2019-07-05               | Pop Remix     | 37i9dQZF1DXcZDD7cfEKhW | pop            | dance pop         | 0.675        | 0.931  | 1    | -3.432   | 0    | 0.0742      | 0.0794       | 2.33e-05         | 0.11     | 0.613   | 124.008 | 176616
75FpbthrwQmzHlBJLuGdC7 | Call You Mine - Keanu Silva Remix                     | The Chainsmokers | 60               | 1nqYsOef1yKKuGOVchbsk6 | Call You Mine - The Remixes                           | 2019-07-19               | Pop Remix     | 37i9dQZF1DXcZDD7cfEKhW | pop            | dance pop         | 0.718        | 0.93   | 7    | -3.778   | 1    | 0.102       | 0.0287       | 9.43e-06         | 0.204    | 0.277   | 121.956 | 169093
1e8PAfcKUYoKkxPhrHqw4x | Someone You Loved - Future Humans Remix               | Lewis Capaldi    | 69               | 7m7vv9wlQ4i0LFuJiE2zsQ | Someone You Loved (Future Humans Remix)               | 2019-03-05               | Pop Remix     | 37i9dQZF1DXcZDD7cfEKhW | pop            | dance pop         | 0.65         | 0.833  | 1    | -4.672   | 1    | 0.0359      | 0.0803       | 0                | 0.0833   | 0.725   | 123.976 | 189052
7fvUMiyapMsRRxr07cU8Ef | Beautiful People (feat. Khalid) - Jack Wins Remix     | Ed Sheeran       | 67               | 2yiy9cd2QktrNvWC2EUi0k | Beautiful People (feat. Khalid) [Jack Wins Remix]     | 2019-07-11               | Pop Remix     | 37i9dQZF1DXcZDD7cfEKhW | pop            | dance pop         | 0.675        | 0.919  | 8    | -5.385   | 1    | 0.127       | 0.0799       | 0                | 0.143    | 0.585   | 124.982 | 163049
2OAylPUDDfwRGfe0lYqlCQ | Never Really Over - R3HAB Remix                       | Katy Perry       | 62               | 7INHYSeusaFlyrHSNxm8qH | Never Really Over (R3HAB Remix)                       | 2019-07-26               | Pop Remix     | 37i9dQZF1DXcZDD7cfEKhW | pop            | dance pop         | 0.449        | 0.856  | 5    | -4.788   | 0    | 0.0623      | 0.187        | 0                | 0.176    | 0.152   | 112.648 | 187675
6b1RNvAcJjQH73eZO4BLAB | Post Malone (feat. RANI) - GATTÜSO Remix              | Sam Feldt        | 69               | 6703SRPsLkS4bPtMFFJes1 | Post Malone (feat. RANI) [GATTÜSO Remix]              | 2019-08-29               | Pop Remix     | 37i9dQZF1DXcZDD7cfEKhW | pop            | dance pop         | 0.542        | 0.903  | 4    | -2.419   | 0    | 0.0434      | 0.0335       | 4.83e-06         | 0.111    | 0.367   | 127.936 | 207619
7bF6tCO3gFb8INrEDcjNT5 | Tough Love

In [30]:
survey = Table().read_table('Math211_ClassSurvey_1_23_Export.csv')

In [31]:
survey

Do you have a Costco membership? | How many cars do you own? | Do you prefer personally driving or relying on other transportation? | How many siblings do you have? | What is your favorite genre of music? | Do you prefer online shopping or in person shopping? | What type of food do you prefer? | Are you lactose intolerant? | How many close friends do you have? | How many kids do you have? | Are you a dog or cat person? | What color lightsaber would you pick? | What is your starter Pokemon? | What is your average daily cellular screen time?
Yes                              | 1                         | driving                                                              | 0                              | electronic                            | online shopping                                      | Mexican                          | No                          | 5                                   | 2                          | dog                          | green blue                            | Charmander                    | more than 5 hours
No                               | 1                         | driving                                                              | 2                              | pop                                   | online shopping                                      | Japanese                         | No                          | 12                                  | 0                          | cat                          | white                                 | Bulbasaur                     | more than 5 hours
Yes                              | 1                         | driving                                                              | 1                              | Alternative                           | online shopping                                      | Japanese                         | No                          | 5                                   | 1                          | dog                          | purple                                | Charmander                    | 3 - 4 hours
Yes                              | 1                         | driving                                                              | 1.5                            | Alt                                   | online shopping                                      | Japanese                         | No                          | 9                                   | 1                          | dog                          | orange                                | Squirtle                      | 1 - 2 hours
Yes                              | 1                         | driving                                                              | 0                              | R & B                                 | in person shopping                                   | Japanese                         | No                          | 8                                   | 0                          | dog                          | purple                                | Charmander                    | more than 5 hours
Yes                              | 1                         | driving                                                              | 0                              | rap                                   | online shopping                                      | Chinese                          | No                          | 6                                   | 3                          | cat                          | purple                                | Charmander                    | more than 5 hours
Yes                              | 1                         | other transportation                                                 | 1                              | pop                                   | in person shopping                                   | Mexican                          | No                          | 5                                   | 1          

In [33]:
spotify.show(3)

### Taking a look at the Table

Whenever we want to take a look at the table itself. 
<img src="Table_show.png" alt="drawing" width="1200"/>

In [32]:
survey.show(100)

### Identifying the Dimensions of a Table

In other words, the number of rows and columns in a given table.
<img src="Table_dimensions.png" alt="drawing" width="1200"/>


In [34]:
spotify.num_rows

32833

In [35]:
spotify.num_columns

23

### Narrowing down the number of columns from the original table 

This can be done by choosing which columns to **only include (i.e. 'select')** or which columns to **exclude (i.e. 'drop')** from the original table. 

<img src="Table_select_drop.png" alt="drawing" width="1200"/>

In [36]:
survey.select("How many cars do you own?","How many siblings do you have?")

How many cars do you own? | How many siblings do you have?
1                         | 0
1                         | 2
1                         | 1
1                         | 1.5
1                         | 0
1                         | 0
1                         | 1
2                         | 2
3                         | 2
1                         | 2
... (104 rows omitted)

In [37]:
spotify = spotify.drop("track_id", "track_album_id","playlist_id")
spotify

track_name                                            | track_artist     | track_popularity | track_album_name                                      | track_album_release_date | playlist_name | playlist_genre | playlist_subgenre | danceability | energy | key  | loudness | mode | speechiness | acousticness | instrumentalness | liveness | valence | tempo   | duration_ms
I Don't Care (with Justin Bieber) - Loud Luxury Remix | Ed Sheeran       | 66               | I Don't Care (with Justin Bieber) [Loud Luxury Remix] | 2019-06-14               | Pop Remix     | pop            | dance pop         | 0.748        | 0.916  | 6    | -2.634   | 1    | 0.0583      | 0.102        | 0                | 0.0653   | 0.518   | 122.036 | 194754
Memories - Dillon Francis Remix                       | Maroon 5         | 67               | Memories (Dillon Francis Remix)                       | 2019-12-13               | Pop Remix     | pop            | dance pop         | 0.726        | 0.815  | 11   | -4.969   | 1    | 0.0373      | 0.0724       | 0.00421          | 0.357    | 0.693   | 99.972  | 162600
All the Time - Don Diablo Remix                       | Zara Larsson     | 70               | All the Time (Don Diablo Remix)                       | 2019-07-05               | Pop Remix     | pop            | dance pop         | 0.675        | 0.931  | 1    | -3.432   | 0    | 0.0742      | 0.0794       | 2.33e-05         | 0.11     | 0.613   | 124.008 | 176616
Call You Mine - Keanu Silva Remix                     | The Chainsmokers | 60               | Call You Mine - The Remixes                           | 2019-07-19               | Pop Remix     | pop            | dance pop         | 0.718        | 0.93   | 7    | -3.778   | 1    | 0.102       | 0.0287       | 9.43e-06         | 0.204    | 0.277   | 121.956 | 169093
Someone You Loved - Future Humans Remix               | Lewis Capaldi    | 69               | Someone You Loved (Future Humans Remix)               | 2019-03-05               | Pop Remix     | pop            | dance pop         | 0.65         | 0.833  | 1    | -4.672   | 1    | 0.0359      | 0.0803       | 0                | 0.0833   | 0.725   | 123.976 | 189052
Beautiful People (feat. Khalid) - Jack Wins Remix     | Ed Sheeran       | 67               | Beautiful People (feat. Khalid) [Jack Wins Remix]     | 2019-07-11               | Pop Remix     | pop            | dance pop         | 0.675        | 0.919  | 8    | -5.385   | 1    | 0.127       | 0.0799       | 0                | 0.143    | 0.585   | 124.982 | 163049
Never Really Over - R3HAB Remix                       | Katy Perry       | 62               | Never Really Over (R3HAB Remix)                       | 2019-07-26               | Pop Remix     | pop            | dance pop         | 0.449        | 0.856  | 5    | -4.788   | 0    | 0.0623      | 0.187        | 0                | 0.176    | 0.152   | 112.648 | 187675
Post Malone (feat. RANI) - GATTÜSO Remix              | Sam Feldt        | 69               | Post Malone (feat. RANI) [GATTÜSO Remix]              | 2019-08-29               | Pop Remix     | pop            | dance pop         | 0.542        | 0.903  | 4    | -2.419   | 0    | 0.0434      | 0.0335       | 4.83e-06         | 0.111    | 0.367   | 127.936 | 207619
Tough Love - Tiësto Remix / Radio Edit                | Avicii           | 68               | Tough Love (Tiësto Remix)                             | 2019-06-14               | Pop Remix     | pop            | dance pop         | 0.594        | 0.935  | 8    | -3.562   | 1    | 0.0565      | 0.0249       | 3.97e-06         | 0.637    | 0.366   | 127.015 | 193187
If I Can't Have You - Gryffin Remix                   | Shawn Mendes     | 67               | If I Can't Have You (Gryffin Remix)                   | 2019-06-20               | Pop Remix     | pop            | dance pop         | 0.642        | 0.818  | 2    | -4.552   | 1    | 0.032       | 0.0567       | 0                | 0.0919   | 0.59   

### Sorting columns of a table

This is our first method (i.e. 'action') that contains an optional argument:
<img src="Table_sort.png" alt="drawing" width="1200"/>

If you want to sort from small -> large, or A - Z, then we will sort in **ascending** order. <br>
If you want to sort from large -> small, or Z - A, then we will sort in **descending** order.

In [40]:
spotify.sort("track_album_release_date")

track_name                            | track_artist           | track_popularity | track_album_name                                        | track_album_release_date | playlist_name                                                | playlist_genre | playlist_subgenre  | danceability | energy | key  | loudness | mode | speechiness | acousticness | instrumentalness | liveness | valence | tempo   | duration_ms
Mess Around                           | Ray Charles            | 59               | Ray Charles (aka: Hallelujah, I Love Her So)            | 1957-01-01               | The 1950s/1960s/1970s/1980s/1990s/2000s/2010s with pop/r ... | r&b            | urban contemporary | 0.565        | 0.962  | 8    | -2.981   | 1    | 0.064       | 0.437        | 0                | 0.056    | 0.906   | 148.808 | 160227
Long Tall Sally (The Thing)           | Little Richard         | 1                | Here's Little Richard [Remastered & Expanded]           | 1957-03                  | Blues Rock                                                   | rock           | classic rock       | 0.474        | 0.598  | 5    | -5.023   | 1    | 0.0973      | 0.768        | 0                | 0.0841   | 0.917   | 184.484 | 131853
Jailhouse Rock                        | Elvis Presley          | 73               | Elvis' Golden Records                                   | 1958-03-21               | Blues Rock                                                   | rock           | classic rock       | 0.647        | 0.582  | 10   | -9.538   | 0    | 0.0755      | 0.41         | 1.93e-06         | 0.0715   | 0.915   | 167.396 | 146480
At Last - Single Version              | Etta James             | 25               | At Last!                                                | 1960                     | The 1950s/1960s/1970s/1980s/1990s/2000s/2010s with pop/r ... | r&b            | urban contemporary | 0.168        | 0.326  | 5    | -9.981   | 1    | 0.0324      | 0.721        | 0.0006           | 0.316    | 0.322   | 174.794 | 182400
(What A) Wonderful World - Remastered | Sam Cooke              | 13               | The Wonderful World Of Sam Cooke (Remastered)           | 1960                     | The 1950s/1960s/1970s/1980s/1990s/2000s/2010s with pop/r ... | r&b            | urban contemporary | 0.524        | 0.543  | 11   | -9.889   | 1    | 0.0397      | 0.734        | 0                | 0.275    | 0.877   | 128.091 | 125507
Jingle Bells                          | Ella Fitzgerald        | 11               | Ella Wishes You A Swinging Christmas (Expanded Edition) | 1960                     | Christmas Soul                                               | r&b            | neo soul           | 0.688        | 0.7    | 7    | -6.295   | 1    | 0.0757      | 0.73         | 0                | 0.727    | 0.876   | 119.117 | 142547
At Last - Single Version              | Etta James             | 15               | Love Songs                                              | 1960                     | Sexy Soul 2020                                               | r&b            | neo soul           | 0.165        | 0.29   | 5    | -9.881   | 1    | 0.0316      | 0.701        | 0.00113          | 0.286    | 0.241   | 174.61  | 179893
Paloma Negra                          | Chavela Vargas         | 47               | Chavela Vargas                                          | 1961-10-26               | Urban contemporary                                           | r&b            | urban contemporary | 0.585        | 0.036  | 2    | -14.145  | 1    | 0.0418      | 0.859        | 3.34e-06         | 0.0908   | 0.433   | 151.223 | 198760
Green Onions                          | Booker T. & the M.G.'s | 64               | Green Onions                                            | 1962                     | Supernatural Classic Rock                                    | rock           | classic rock       | 0.816        | 0.514  | 10   | -8.741   | 1    | 0.0339      | 0.767        | 0.

### Filtering our table based upon a condition

Sometimes we want to narrow down our list of individuals based upon a status or condition and look at them in their own table. We can do so using the following method: 
<img src="Table_where.png" alt="drawing" width="1200"/>

Note that our condition is defined as a predicate. The table of predicates below: 
<img src="Table_where_predicates.png" alt="drawing" width="1200"/>

In [42]:
survey.where("What is your starter Pokemon?",are.equal_to("Squirtle"))

Do you have a Costco membership? | How many cars do you own? | Do you prefer personally driving or relying on other transportation? | How many siblings do you have? | What is your favorite genre of music? | Do you prefer online shopping or in person shopping? | What type of food do you prefer? | Are you lactose intolerant? | How many close friends do you have? | How many kids do you have? | Are you a dog or cat person? | What color lightsaber would you pick? | What is your starter Pokemon? | What is your average daily cellular screen time?
Yes                              | 1                         | driving                                                              | 1.5                            | Alt                                   | online shopping                                      | Japanese                         | No                          | 9                                   | 1                          | dog                          | orange                                | Squirtle                      | 1 - 2 hours
Yes                              | 1                         | other transportation                                                 | 1                              | pop                                   | in person shopping                                   | Mexican                          | No                          | 5                                   | 1                          | cat                          | purple                                | Squirtle                      | 1 - 2 hours
Yes                              | 3                         | driving                                                              | 2                              | rock                                  | online shopping                                      | Chinese                          | No                          | 3                                   | 1                          | dog                          | black                                 | Squirtle                      | 3 - 4 hours
Yes                              | 1                         | other transportation                                                 | 3                              | Mexican Banda                         | in person shopping                                   | Japanese                         | Yes                         | 3                                   | 0                          | cat                          | yellow                                | Squirtle                      | 3 - 4 hours
Yes                              | 3                         | driving                                                              | 4                              | kpop                                  | in person shopping                                   | Japanese                         | No                          | 5                                   | 0                          | cat                          | green blue                            | Squirtle                      | more than 5 hours
Yes                              | 0                         | other transportation                                                 | 13                             | R & B                                 | online shopping                                      | Japanese                         | Yes                         | 5                                   | 1                          | neither                      | green blue                            | Squirtle                      | 3 - 4 hours
No                               | 1                         | other transportation                                                 | 1                              | rap                                   | online shopping                                      | Mexican                          | I don't know                | 10                                  | 0                          | 

# Building Tables with `tbl.with_column`

We can append columns to a table using the following method. 
<img src="tbl.with_column.png" alt="drawing" width="1200"/>

In [43]:
subscription = make_array('Netflix','HBO Max','Hulu','Crunchyroll','Spotify','DoorDash','AmazonPrime','Discord Nitro')
subscription

array(['Netflix', 'HBO Max', 'Hulu', 'Crunchyroll', 'Spotify', 'DoorDash',
       'AmazonPrime', 'Discord Nitro'],
      dtype='<U13')

In [44]:
#Amazon and Discord are annual fees
month_fee_cost = make_array(19.99,14.99,9.99,9.99,9.99,9.99,(130/12),(169.97/12))
month_fee_cost

array([ 19.99      ,  14.99      ,   9.99      ,   9.99      ,
         9.99      ,   9.99      ,  10.83333333,  14.16416667])

In [45]:
bryans_monthly_subscriptions = Table().with_columns('Subscription',subscription,'$$ per month',month_fee_cost)
bryans_monthly_subscriptions

Subscription  | $$ per month
Netflix       | 19.99
HBO Max       | 14.99
Hulu          | 9.99
Crunchyroll   | 9.99
Spotify       | 9.99
DoorDash      | 9.99
AmazonPrime   | 10.8333
Discord Nitro | 14.1642

In [46]:
#annual_cost = bryans_monthly_subscriptions.column('$$ per month') * 12
#OR, below
annual_cost = month_fee_cost *12 
annual_cost

array([ 239.88,  179.88,  119.88,  119.88,  119.88,  119.88,  130.  ,
        169.97])

In [47]:
new_table = bryans_monthly_subscriptions.with_column('$$ each year',annual_cost)#.drop('$$ per month')
new_table

Subscription  | $$ per month | $$ each year
Netflix       | 19.99        | 239.88
HBO Max       | 14.99        | 179.88
Hulu          | 9.99         | 119.88
Crunchyroll   | 9.99         | 119.88
Spotify       | 9.99         | 119.88
DoorDash      | 9.99         | 119.88
AmazonPrime   | 10.8333      | 130
Discord Nitro | 14.1642      | 169.97

In [48]:
sum(annual_cost)

1199.25